language: java                                            
jdk:                                                     
- openjdk8
services: 
- docker
script: 
- mvn clean install                                    
- docker build -t tanishqj13/scientific-calculator
deploy: 
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
notifications:
  email: tanishq.jaswani@iiitb.ac.in
