language: java                                            
jdk:                                                     
- openjdk8                                            
services:                                                
- docker                                                
script: mvn clean install                                    
deploy:                                                  
  provider: pages                                        
  skip-cleanup: true                                        
  github-token: $GITHUB_TOKEN                                    
  on:                                                        
    branch: master
notifications:
  email: Tanishq.Jaswani@iiitb.ac.in
