language: java                                            
jdk:                                                     
- openjdk8
services: 
- docker
script: 
- mvn clean install
after_success:
- docker build -t tanishqj13/scientific-calculator
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push tanishqj13/scientific-calculator
#deploy: 
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN
#  on:
#    branch: master
notifications:
  email: tanishq.jaswani@iiitb.ac.in
