language: java                                            
jdk:                                                     
- openjdk8                                            
                                                
script: mvn clean install                                    

notifications:
  email: tanishq.jaswani@iiitb.ac.in
